version: '0.0.1'

services:

  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --auth=scram-sha-256' 
    volumes:
      - ./pgdbdata:/var/lib/postgresql/data/
    ports:
      - "5434:5432"
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  redis: 
    image: redislabs/redismod
    container_name: redis
    expose:
      - 6379
  
  syperlink:
    build: .
    volumes:
      - ./migrations:/superlink/migrations
    expose:
      - 5000
    depends_on:
      - db
      - redis
  
  nginx:
    build: 
      context: ./
      dockerfile: ./nginx/Dockerfile
    volumes:
      - static_volume:/home/nginx/static
    ports:
      - 80:80
    depends_on:
      - syperlink


volumes:
  pgdbdata: null
  static_volume: null
  migrations: null