"""link blocking

Revision ID: deff4420c104
Revises: 
Create Date: 2025-01-08 20:19:00.047801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'deff4420c104'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('is_blocked', sa.Boolean())) # deleted nullable=False
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('link', 'is_blocked')
    # ### end Alembic commands ###
